documentation:
  documents: '_documentation/**/*.md'
  origin: '_documentation'
  base_url_path: ''
api:
  documents: '_api/**/*.md'
  origin: '_api'
  base_url_path: '/api'
tutorials:
  documents: '_tutorials/**/*.md'
  origin: '_tutorials'
  base_url_path: '/use-cases'
