navigation_weight:
  application: 0
  messaging: 1
  sms: 1
  voice: 2
  verify: 3
  number-insight: 4
  Messages: 5
  Dispatch: 6
  numbers: 98
  account: 99
  vonage-business-cloud: 7

  number-programmability: 1
  vbc-apis: 2
  getting-started: 1
  account-api: 2
  extension-api: 3
  user-api: 4
  integration-suite: 3

  Onboarding: 0
  Overview: 1
  Developer Preview: 2
  tasks: 3
  quickstarts: 3
  guides: 4
  code-snippets: 5

  tutorials: 6
  Troubleshooting: 7
  API Reference: 7
  conversation: 8

  voice-api: 1
  sip: 2

  client-sdk: 30
  NCCO Reference: 40
  sdk-documentation: 40
  API Reference: 50

  Overview: 1
  setup: 2
  concepts: 3
  in-app-messaging: 4
  in-app-voice: 5
  in-app-video: 6

  messages: 1
  dispatch: 2

  secret-management: 30

navigation_overrides:
  application:
    svg: 'flow'
    svgColor: 'indigo'
  concepts:
    navigation_weight: 0
    svg: 'mind-map'
    svgColor: 'red'
  messaging:
    svg: 'message'
    svgColor: 'purple'
  voice:
    svg: 'phone'
    svgColor: 'green'
    voice-api:
      guides:
        websockets:
          label: 'Beta'
  verify:
    svg: 'lock'
    svgColor: 'indigo'
  number-insight:
    svg: 'file-search'
    svgColor: 'orange'
  account:
    svg: 'user'
    svgColor: 'blue'
  redact:
    label: 'Dev Preview'
    svg: 'lock'
    svgColor: 'red'
  client-sdk:
    svg: 'queue'
    svgColor: 'teal'
    label: 'Dev Preview'
    sdk-documentation:
      link: false
      collapsible: false
  numbers:
    svg: 'phone-number'
    svgColor: 'red'
  audit:
    svg: 'file-search'
    svgColor: 'green'
    label: 'Beta'
  messages:
    svg: 'chat'
    svgColor: 'purple'
    label: 'Beta'
    code-snippets:
      collapsible: false
  dispatch:
    svg: 'flow'
    svgColor: 'purple'
    label: 'Beta'
  conversation:
    svg: 'message'
    svgColor: 'teal'
    label: 'Dev Preview'
    code-snippets:
      collapsible: false
  vonage-business-cloud:
    svg: 'telephone'
    svgColor: 'green'
  contribute:
    administration:
      navigation_weight: 9999
